M365_BASE_KNOWLEDGE_RESOURCES = (
    {
        "id": "outlook_delivery_domain",
        "service": "outlook",
        "intent": "email_delivery",
        "title": "Outlook message returned or recipient domain error",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "outlook", "email", "mail", "send", "sent", "returned",
            "sent back", "came back", "bounce", "bounced", "undeliverable",
            "domain", "domain does not exist", "domain not found",
            "recipient", "delivery", "address",
        ),
        "steps": (
            "Check the recipient address for typos, extra spaces, or a misspelled domain after the @ symbol.",
            "Try sending the same message from Outlook on the web at outlook.com or microsoft365.com.",
            "If Outlook on the web also fails, ask the recipient to confirm the correct address or send you a fresh message to reply to.",
            "If the message still returns, copy the full bounce-back text so support can check the recipient domain and mail routing.",
        ),
    },
    {
        "id": "teams_audio_devices",
        "service": "teams",
        "intent": "unknown",
        "title": "Teams microphone, speaker, or meeting audio issue",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "teams", "meeting", "call", "microphone", "mic", "camera",
            "speaker", "audio", "sound", "hear me", "cant hear",
            "can't hear", "mute", "muted", "device",
            "teems", "meetin", "nobody hears", "nobody hears me",
            "they cant hear", "nobody can hear", "my mic", "im muted",
            "silent", "cant hear me",
        ),
        "steps": (
            "Go to: Settings > System > Sound and confirm the correct Input or Output device is selected.",
            "Go to: Settings > Privacy & security > Microphone or Camera and confirm app access is turned on.",
            "In Teams, go to: Settings > Devices and choose the correct microphone, speaker, and camera.",
            "Test in the meeting after changing devices however if it does not work leave and rejoin so Teams refreshes the audio session.",
        ),
    },
    {
        "id": "outlook_mailbox_sync_search",
        "service": "outlook",
        "intent": "sync",
        "title": "Outlook inbox, mailbox sync, or missing mail issue",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "outlook", "email", "emails", "mail", "inbox", "mailbox",
            "missing", "not loading", "not updating", "sync", "search",
            "old mail", "old email", "messages", "folder",
            "outluk", "outlok", "zero results", "hasnt loaded", "serach",
            "nothing comes up", "searched", "no mail", "messages gone",
        ),
        "steps": (
            "Try Outlook on the web at outlook.com or microsoft365.com to confirm whether the mail is missing from the account or only the app.",
            "In Outlook, check the current folder, focused inbox, filters, and search terms.",
            "Refresh or restart Outlook, then check whether new mail appears.",
            "If Outlook on the web has the mail but the desktop app does not, the desktop mailbox cache may need repair or resync.",
        ),
    },
    {
        "id": "onedrive_sync_pending",
        "service": "onedrive",
        "intent": "sync",
        "title": "OneDrive sync stuck, pending, or not uploading",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "onedrive", "one drive", "one drv", "sync", "syncing",
            "pending", "upload", "download", "cloud", "files",
            "stuck", "not updating", "not uploading",
            "ondrive", "uploadin", "not syncing up", "pending upload",
            "nothing is syncing", "wont upload", "sync stuck",
        ),
        "steps": (
            "Select the OneDrive cloud icon and confirm you are signed in with the correct Microsoft account.",
            "Pause syncing, wait a few seconds, then resume syncing from the OneDrive cloud icon.",
            "Check the OneDrive activity panel for file-specific errors such as invalid characters, long paths, or permission problems.",
            "If only one file is stuck, rename it or move it to a shorter folder path, then let OneDrive retry.",
        ),
    },
    {
        "id": "windows_display_detect",
        "service": "windows",
        "intent": "unknown",
        "title": "Windows second monitor or display not detected",
        "source": "Local Windows support playbook",
        "keywords": (
            "windows", "monitor", "screen", "display", "second monitor",
            "second screen", "external monitor", "dock", "docking station",
            "usb c", "usb-c", "hdmi", "displayport", "not detected",
        ),
        "steps": (
            "Confirm the monitor is powered on and set to the correct input source.",
            "Reconnect the cable or dock, then press Windows + P and choose Extend or Duplicate.",
            "Go to: Settings > System > Display > Multiple displays and select Detect.",
            "If the display still does not appear, open Device Manager and check for display adapter or USB-C dock warnings.",
        ),
    },
    {
        "id": "camera_permission",
        "service": "teams",
        "intent": "unknown",
        "title": "Camera blocked by app, browser, or Windows permissions",
        "source": "Local Windows and Teams support playbook",
        "keywords": (
            "camera", "webcam", "cam", "blocked", "permission",
            "permissions", "privacy", "browser", "teams", "allow",
            "teems", "permision", "shows black", "black screen",
            "camera blocked", "camera not working", "in use by another",
            "camera permission", "video blocked", "cant see camera",
        ),
        "steps": (
            "Go to: Settings > Privacy & security > Camera and turn on camera access.",
            "Confirm the browser or desktop app is allowed to use the camera.",
            "If using a browser, select the lock icon near the address bar and allow camera access for the site.",
            "Open the app's device settings and select the correct camera.",
        ),
    },
    {
        "id": "bluetooth_audio_pairing",
        "service": "windows",
        "intent": "unknown",
        "title": "Bluetooth headset, speaker, keyboard, or mouse will not connect",
        "source": "Local Windows support playbook",
        "keywords": (
            "bluetooth", "headphones", "headset", "speaker", "keyboard",
            "mouse", "pair", "paired", "connect", "connected", "wireless",
            "disconnectin", "keeps dropping", "drops", "randomly drops",
            "keeps disconnecting", "drops connection", "disconnecting",
            "random disconnect", "bluetooth drops", "headset disconnects",
        ),
        "steps": (
            "Go to: Settings > Bluetooth & devices and confirm Bluetooth is turned on.",
            "Remove the device from Bluetooth devices, then put it back in pairing mode.",
            "Pair the device again and confirm it shows as connected.",
            "For audio devices, go to: Settings > System > Sound and select the device under Output or Input.",
        ),
    },
    {
        "id": "printer_scanner_missing",
        "service": "windows",
        "intent": "unknown",
        "title": "Printer or scanner missing in Windows",
        "source": "Local Windows support playbook",
        "keywords": (
            "printer", "print", "scanner", "scan", "not found",
            "missing", "offline", "printers", "scanners",
            "disapeared", "disappeared", "vanished", "not showing up",
            "gone from list", "cant print", "printer gone", "printer missing",
            "printer vanished", "printer offline", "print not working",
        ),
        "steps": (
            "Confirm the printer or scanner is powered on and connected to the same network or cable.",
            "Go to: Settings > Bluetooth & devices > Printers & scanners.",
            "Remove the device if it is stuck or offline, then add it again.",
            "If Windows still cannot find it, check Windows Update or the manufacturer's driver utility.",
        ),
    },
    {
        "id": "usb_drive_missing",
        "service": "windows",
        "intent": "crash",
        "title": "USB drive not showing in File Explorer",
        "source": "Local Windows support playbook",
        "keywords": (
            "usb", "usb drive", "flash drive", "thumb drive", "external drive",
            "file explorer", "drive letter", "not showing", "not detected",
            "not showin up", "explrer", "doesnt show up", "drive not showing",
            "flash drive not showing", "usb not showing", "drive not found",
            "drive missing", "not recognized", "light is on",
        ),
        "steps": (
            "Try a different USB port and reconnect the drive.",
            "Open File Explorer and check whether Windows assigned the drive a letter.",
            "Open Device Manager and check for USB or disk drive warning icons.",
            "If the drive appears in Disk Management but not File Explorer, it may need a drive letter assigned.",
        ),
    },
    {
        "id": "sharepoint_access_denied",
        "service": "sharepoint",
        "intent": "sign_in",
        "title": "SharePoint file or site says access denied",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "sharepoint", "share point", "access denied", "permission",
            "permissions", "file", "site", "link", "cannot access",
            "sharepoiint", "sharepiont", "shaepoint", "acess denied",
            "permision", "no access", "cant access", "need access",
            "get permission", "denied",
        ),
        "steps": (
            "Open the SharePoint link in a browser and confirm you are signed in with the correct Microsoft account.",
            "Try opening the file from the SharePoint site instead of an old shared link.",
            "If it still says access denied, ask the owner to share it again or verify your permissions.",
            "If other users also cannot access it, the owner or admin should check site permissions.",
        ),
    },
    {
        "id": "office_app_crash",
        "service": "microsoft 365",
        "intent": "crash",
        "title": "Office app crashing, freezing, or failing to open",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "word", "excel", "powerpoint", "office", "crash", "crashing",
            "freeze", "frozen", "not responding", "error", "wont open",
            "won't open", "save failed",
            "crashin", "freezin", "keeps crashin", "keeps freezin", "wont respond",
            "randomly crashing", "randomly freezing", "keeps crashing",
            "keeps freezing", "crashes n freezes", "freezes randomly",
        ),
        "steps": (
            "Close the Office app fully and reopen it from the Start menu.",
            "Try opening the file from File > Open instead of double-clicking it.",
            "If only one file fails, save a copy to Desktop or OneDrive and try opening the copy.",
            "If every Office app fails, restart Windows and check for Office updates.",
        ),
    },
    {
        "id": "microsoft_account_sign_in",
        "service": "microsoft account",
        "intent": "sign_in",
        "title": "Microsoft account sign-in, password, or Authenticator issue",
        "source": "Local Microsoft account support playbook",
        "keywords": (
            "microsoft account", "ms account", "sign in", "signin", "login",
            "password", "authenticator", "verification code", "security code",
            "2fa", "locked out", "wrong password",
            "pasword", "acunt", "failin", "wont accept", "keeps sayin",
            "microsoft acunt", "cant sign in", "password wrong", "signin failing",
            "microsft account", "microsoft acct",
        ),
        "steps": (
            "Try signing in at microsoft365.com to confirm whether the issue affects the whole account.",
            "If the password is not accepted, use the Forgot password option on the Microsoft sign-in page.",
            "If Authenticator does not prompt, choose another verification method if available.",
            "If no verification method works, use account recovery or create a support ticket with the exact sign-in message.",
        ),
    },
)
