EXPANDED_KNOWLEDGE_RESOURCES = (
    # ------------------------------------------------------------------ OUTLOOK
    {
        "id": "outlook_no_incoming_mail",
        "service": "outlook",
        "intent": "email_delivery",
        "title": "Outlook not receiving emails or inbox not updating",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "outlook", "email", "emails", "mail", "not receiving", "not getting",
            "no emails", "inbox empty", "not arriving", "havent received",
            "haven't received", "missing emails", "emails stopped",
            "email not coming in", "new mail not showing", "outlok", "recieving",
            "emails not coming through", "inbox not updating",
            "havent gotten", "no emails coming", "not getting any",
            "inbox empty today", "no new mail", "emails not arriving",
        ),
        "steps": (
            "Open outlook.com in a browser and check whether the emails are there — if they are, the issue is with your desktop app, not your account.",
            "In the desktop app, check the Focused Inbox, Other tab, Junk folder, and any rules that could be sorting mail away automatically.",
            "Check that your mailbox is not full by going to File > Info — a full mailbox stops new emails from arriving.",
            "If mail shows on the web but not in the app, close Outlook fully, reopen it, and give it a few minutes to finish syncing before checking again.",
        ),
    },
    {
        "id": "outlook_send_stuck_outbox",
        "service": "outlook",
        "intent": "email_delivery",
        "title": "Outlook cannot send email or message stuck in Outbox",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "outlook", "email", "send", "sending", "cant send", "stuck",
            "outbox", "not sending", "email wont send", "email won't send",
            "draft", "queued", "stuck in outbox", "send failed", "outbok",
            "sendng", "message stuck", "email not going out",
            "wont send", "email stuck", "in my outbox", "been stuck",
            "not going out", "email in outbox",
        ),
        "steps": (
            "Open your Outbox folder and move the stuck message to Drafts — a message stuck in Outbox can block everything behind it.",
            "Check that Outlook is online and not in Work Offline mode by looking at the status bar at the bottom of the window.",
            "Try sending a short test email to yourself — if it goes through, the original message may have an attachment that is too large.",
            "If nothing sends, sign out of Outlook under File > Account Settings, sign back in, and try again or send the message from outlook.com instead.",
        ),
    },
    {
        "id": "outlook_password_prompt",
        "service": "outlook",
        "intent": "sign_in",
        "title": "Outlook keeps asking for password or signing out repeatedly",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "outlook", "password", "keeps asking", "signing out", "sign in",
            "prompting password", "password prompt", "keeps logging out",
            "cant stay signed in", "re-entering password", "password again",
            "keeps disconnecting", "outlok", "pasword", "passord",
            "authentication", "credentials", "outlook keeps logging me out",
            "popping up", "pop up", "prompting", "keeps prompting",
            "asking for password", "every few mins", "password popup",
        ),
        "steps": (
            "Check that your Windows account and Outlook are both using the same Microsoft account — a mismatch causes repeated sign-in prompts.",
            "Go to: Control Panel > Credential Manager > Windows Credentials and remove any old Outlook or Microsoft entries, then reopen Outlook and sign in fresh.",
            "Confirm your password has not expired by signing in at microsoft365.com — if it fails there too, reset your password first.",
            "If the prompt keeps appearing, remove your account in Outlook under File > Account Settings, add it back, and let Outlook re-authenticate.",
        ),
    },
    {
        "id": "outlook_signature_missing",
        "service": "outlook",
        "intent": "unknown",
        "title": "Outlook email signature missing or not saving",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "outlook", "signature", "email signature", "missing", "not saving",
            "not showing", "disappeared", "auto signature", "sign off",
            "footer", "no signature", "signature gone", "signatrue", "signture",
            "siganture", "signature not working", "signature not added automatically",
            "custom signature", "email footer",
            "signature wont save", "wont save", "cant save signature",
            "signature disappeared", "outlok signature", "signature missing",
            "outlok", "email signatrue", "save again", "save signature",
        ),
        "steps": (
            "Open Outlook and go to: File > Options > Mail > Signatures to confirm your signature is still saved there.",
            "In the signature settings, make sure the signature is assigned to both New messages and Replies/Forwards under your email account.",
            "If the signature is blank or missing, delete it, create a new one, and save.",
            "Signatures are not synced automatically across devices — you will need to recreate it on each device or set it up at outlook.com under Settings > Compose and reply.",
        ),
    },
    {
        "id": "outlook_search_broken",
        "service": "outlook",
        "intent": "unknown",
        "title": "Outlook search not working or returning old results",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "outlook", "search", "not working", "no results", "old results",
            "search broken", "cant find email", "cant find message",
            "search not finding", "search bar", "search empty", "wrong results",
            "missing search results", "outlok", "serach", "seach",
            "email search", "find email", "search not showing",
            "zero results", "got nothing", "nothing coming up",
            "search returns nothing", "typed and got nothing",
        ),
        "steps": (
            "Close Outlook, wait a few seconds, reopen it, and try the search again — search can fail when the app first starts.",
            "Make sure you are searching All Mailboxes and not just the current folder — look for the scope option below the search bar.",
            "Go to: File > Options > Search and click Indexing Options, then confirm Outlook is in the indexed locations list.",
            "If the index is corrupted, click Rebuild in Indexing Options — this can take up to an hour but will fix most search problems.",
        ),
    },
    {
        "id": "outlook_attachment_open",
        "service": "outlook",
        "intent": "unknown",
        "title": "Cannot open or preview email attachments in Outlook",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "outlook", "attachment", "attachments", "cant open", "cannot open",
            "preview", "file", "opens blank", "not loading", "blocked",
            "attachment wont open", "cannot preview", "email file",
            "attacment", "attachement", "attchment", "document wont open",
            "attachment error", "attached file",
            "just spins", "wont open", "spinning", "cant open attachment",
            "pdf wont open", "file wont open", "attachment just spins",
        ),
        "steps": (
            "Try saving the attachment to your Downloads folder first, then open it from there rather than directly inside Outlook.",
            "Check that you have an app installed that can open that file type — for example, a .pdf file needs a PDF reader.",
            "If Outlook shows a yellow warning bar blocking the preview, click Enable Editing or trust the document if you recognize the sender.",
            "If no attachments open at all, go to: File > Options > Trust Center > Trust Center Settings > Attachment Handling and confirm previewing is not disabled.",
        ),
    },
    {
        "id": "outlook_junk_filter",
        "service": "outlook",
        "intent": "unknown",
        "title": "Outlook junk filter too aggressive or spam getting through",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "outlook", "junk", "spam", "junk mail", "junk folder", "spam filter",
            "too aggressive", "blocking good emails", "important emails in junk",
            "good emails going to junk", "spam not blocked", "getting spam",
            "jnuk", "spamm", "junk email", "filter", "phishing",
            "blocked sender", "safe sender",
            "jnuk folder", "going to junk", "emails in junk",
            "landing in junk", "real emails in junk", "clients going to junk",
        ),
        "steps": (
            "If real emails are landing in Junk, right-click one and choose Junk > Never Block Sender to whitelist that address.",
            "If spam is reaching your inbox, right-click a spam email and choose Junk > Block Sender to add them to your blocked list.",
            "Go to: Home > Junk > Junk Email Options and raise the protection level — High catches more spam but may occasionally catch real mail too.",
            "For persistent spam problems, check your Outlook.com settings online at outlook.com — the server-side filter is stronger than the desktop app filter.",
        ),
    },
    {
        "id": "outlook_meeting_invite",
        "service": "outlook",
        "intent": "unknown",
        "title": "Meeting invite not appearing in Outlook calendar",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "outlook", "meeting", "invite", "calendar", "meeting invite",
            "not showing", "missing", "accepted invite", "meeting not in calendar",
            "invitation", "calender", "calander", "meeting disappeared",
            "meeting not added", "accept meeting", "teams meeting",
            "scheduled meeting", "invte", "inivte",
            "meetin invte", "never got", "never showed up",
            "meetin invite", "invite never came", "invite not in calendar",
        ),
        "steps": (
            "Open your calendar in the app and also at outlook.com and check if the meeting appears in one place but not the other.",
            "If the invite arrived in your inbox as an email, open it and click Accept — the meeting will not appear on your calendar until you accept it.",
            "If you already accepted but it is still missing, close Outlook, reopen it, and give it a minute to sync.",
            "If the organizer sent the invite to a shared mailbox or a different email address, open that calendar separately to find it.",
        ),
    },
    {
        "id": "outlook_out_of_office",
        "service": "outlook",
        "intent": "unknown",
        "title": "Out of office or automatic reply not turning on or not sending",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "outlook", "out of office", "automatic reply", "auto reply",
            "ooo", "not sending", "not turning on", "vacation reply",
            "away message", "auto reply not working", "automatic reply not working",
            "out of ofice", "automtic reply", "out of offce", "auto-reply",
            "away", "setting up out of office",
            "nobody getting it", "not going out", "reply not sending",
            "auto reply off", "nobody receiving it", "turned on but not sending",
        ),
        "steps": (
            "Go to: File > Automatic Replies and confirm the feature is turned on with the dates set to today or a future range.",
            "If you see a message saying your account does not support automatic replies, try setting it up from outlook.com instead — go to Settings > Automatic replies.",
            "On outlook.com, turn on the automatic reply and set the message there — it will send even when your desktop app is closed.",
            "If the reply is on but contacts say they are not receiving it, check that Send replies to everyone is selected rather than just your contacts.",
        ),
    },
    {
        "id": "outlook_shared_mailbox",
        "service": "outlook",
        "intent": "sync",
        "title": "Shared mailbox not showing in Outlook or not loading new mail",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "outlook", "shared mailbox", "shared email", "shared inbox",
            "shared account", "not showing", "not loading", "missing",
            "team mailbox", "group mailbox", "shared folder",
            "shred mailbox", "shaired mailbox", "cant see shared mailbox",
            "shared mail not loading", "delegate", "delegated",
            "vanished", "disappeared", "gone", "outlok shared",
            "mailbox vanished", "shared mailbox gone", "mailbox disappeared",
        ),
        "steps": (
            "Check that your IT admin has given you access to the shared mailbox — without permission it will not appear in Outlook.",
            "Go to: File > Account Settings > Account Settings > your account > More Settings > Advanced and check the Additional Mailboxes list.",
            "If the mailbox is not listed, click Add and type the shared mailbox address to add it manually.",
            "After adding it, close and reopen Outlook — the shared mailbox folder should appear in the left panel within a couple of minutes.",
        ),
    },
    {
        "id": "outlook_auto_read",
        "service": "outlook",
        "intent": "unknown",
        "title": "Emails being marked as read automatically without opening them",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "outlook", "email", "marked as read", "automatically read",
            "read automatically", "opens as read", "read without opening",
            "mark as read", "reading pane", "auto mark read",
            "email marked read", "auot read", "aut read",
            "preview marks as read", "mail reading pane", "single click read",
            "before i open", "automatically marking", "auto marked",
            "being marked", "marked before opening", "reads itself",
        ),
        "steps": (
            "Go to: File > Options > Mail > Reading Pane and uncheck Mark items as read when viewed in the Reading Pane.",
            "You can also set a longer delay before an email is marked as read so scrolling past it does not flag it immediately.",
            "If you want no auto-marking at all, turn off the Reading Pane under View > Reading Pane > Off so emails only open when you double-click them.",
            "If emails are still being marked as read with no action on your part, check whether another device or the Outlook mobile app is opening them first.",
        ),
    },
    {
        "id": "outlook_profile_picture",
        "service": "outlook",
        "intent": "unknown",
        "title": "Profile picture not showing or not updating in Outlook",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "outlook", "profile picture", "photo", "avatar", "picture not showing",
            "picture not updating", "no photo", "wrong photo", "profile photo",
            "contact photo", "change profile picture", "picture not changed",
            "profile pic", "profle picture", "profil photo", "display picture",
            "photo not updating", "old photo",
        ),
        "steps": (
            "Profile pictures sync from your Microsoft account — update your photo at account.microsoft.com under Profile, then wait up to 48 hours.",
            "To speed it up, sign out of Outlook and sign back in after changing the photo online.",
            "If your photo appears in Outlook but not in Teams or other apps, each app may need a separate sign-out and sign-back-in to pick up the change.",
            "Contact photos that are wrong or missing for other people come from your organization's directory — only your IT admin can update someone else's photo there.",
        ),
    },
    # ------------------------------------------------------------------- TEAMS
    {
        "id": "teams_sign_in_loop",
        "service": "teams",
        "intent": "sign_in",
        "title": "Cannot sign in to Teams or Teams stuck in a login loop",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "teams", "sign in", "login", "cant sign in", "login loop",
            "signing in loop", "stuck on sign in", "keeps asking to sign in",
            "teams login", "can't log in", "teams not signing in",
            "teems", "tems", "teams wont log in", "sign in error",
            "account not recognized", "teeams",
            "cant sign into", "sign into teams", "messed up", "wont sign in",
            "both broken", "neither working",
            "login page", "bouncin", "bouncing back", "never gets me in",
            "back to login", "keeps bouncing", "wont let me in",
        ),
        "steps": (
            "Close Teams completely including the system tray icon, then reopen it — the login loop often clears on a fresh start.",
            "Try signing in at teams.microsoft.com in a browser — if that works, the issue is with the desktop app, not your account.",
            "Clear the Teams app cache by pressing Windows + R, typing %appdata%\\Microsoft\\Teams, and deleting everything inside the Cache folder, then sign back in.",
            "If the loop continues, go to: Settings > Accounts > Access work or school, disconnect your work account and reconnect it.",
        ),
    },
    {
        "id": "teams_notifications",
        "service": "teams",
        "intent": "unknown",
        "title": "Teams notifications not working or firing too often",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "teams", "notifications", "not working", "not getting",
            "no alerts", "notification sound", "banners not showing",
            "too many notifications", "constant notifications", "all day alerts",
            "notification spam", "notifcation", "notifiation", "teams alerts",
            "notify", "badge", "message alerts", "notification settings",
            "teems", "tems", "notifcaions", "borken", "not gettin",
            "alerts", "alerts broken", "no alerts at all",
            "muted", "constantley", "constantly", "bombarding",
            "already muted", "still getting", "spamming me",
        ),
        "steps": (
            "In Teams, go to: Settings > Notifications and confirm that notifications are enabled for messages, mentions, and calls.",
            "If Windows is blocking Teams notifications, go to: Settings > System > Notifications and make sure Microsoft Teams is allowed.",
            "For too many notifications, go to Teams Settings > Notifications and change channels to Only @mentions or Off for high-traffic channels.",
            "Check that Do Not Disturb and Focus mode are both off in Windows — either one will silence all Teams notifications.",
        ),
    },
    {
        "id": "teams_status_stuck",
        "service": "teams",
        "intent": "unknown",
        "title": "Teams status stuck on Away, Busy, or Do Not Disturb",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "teams", "status", "away", "busy", "do not disturb", "dnd",
            "status stuck", "wrong status", "status not changing",
            "stuck on away", "stuck on busy", "shows offline", "presence",
            "change status", "cant change status", "status not updating",
            "teems", "tems", "statuss",
            "shows busy", "showing as", "presence wrong", "showing me as",
            "status showing", "showing available", "shows away",
        ),
        "steps": (
            "Click your profile picture at the top of Teams and manually set your status to Available — this overrides auto-detection.",
            "Check whether a scheduled Focus session or an all-day calendar event is automatically setting your status to Do Not Disturb.",
            "Sign out of Teams and sign back in to force the presence service to refresh your status.",
            "If others still see the wrong status after you change it, wait a few minutes — presence updates can take time to sync across all devices.",
        ),
    },
    {
        "id": "teams_chat_missing",
        "service": "teams",
        "intent": "unknown",
        "title": "Teams chat history missing or messages disappeared",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "teams", "chat", "messages", "missing", "disappeared", "gone",
            "chat history", "message history", "past messages",
            "cant find messages", "old messages", "chat gone",
            "deleted chat", "history not showing", "teems",
            "mesages", "messges", "tems", "chat not loading",
            "disapeared", "old chats", "convo", "chats gone",
            "my chats vanished", "conversation gone", "important convo",
        ),
        "steps": (
            "Check that you are signed in to the correct Teams account — if you have multiple accounts, switch at the top of Teams and look in each one.",
            "Use the Teams search bar at the top to search for the name of the person or a word from the missing message.",
            "Teams only shows recent chats in the sidebar — scroll up in the chat or use search to find older messages.",
            "Messages deleted by a user or by a retention policy cannot be recovered — if messages are still missing after searching, contact your IT admin.",
        ),
    },
    {
        "id": "teams_guest_access",
        "service": "teams",
        "intent": "permissions",
        "title": "Guest user cannot access a Teams team or channel",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "teams", "guest", "guest user", "guest access", "cannot access",
            "external user", "outside user", "not in team", "invitation",
            "invite link", "guest invite", "cant join team", "access denied",
            "outside company", "teems", "guset", "guets",
            "external access", "invite not working",
            "acess denied", "channle", "accepted invite", "says empty",
            "channel empty", "gets denied", "accepted but denied",
        ),
        "steps": (
            "Confirm the guest received and accepted the email invitation — without accepting, they will not have access to anything.",
            "Make sure your organization has guest access turned on — this is an admin setting and may need to be enabled by IT.",
            "The guest should sign in at teams.microsoft.com using the exact email address the invite was sent to, not a different one.",
            "If the guest can sign in but cannot see the team, the team owner should re-add them from the team's Members settings.",
        ),
    },
    {
        "id": "teams_screen_share",
        "service": "teams",
        "intent": "unknown",
        "title": "Cannot share screen in Teams or shared screen is blank",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "teams", "screen share", "screenshare", "share screen",
            "blank screen", "black screen", "cant share", "sharing not working",
            "screen sharing", "present", "presenting", "screen blank",
            "other people cant see", "cant see my screen", "teems",
            "screan share", "screen shre", "screen sharing not working",
            "sharin", "white screen", "everyone sees blank",
            "shared screen blank", "blank to others", "shows blank",
        ),
        "steps": (
            "During a meeting, click the up-arrow Share icon and select the specific window or screen you want to share.",
            "Go to: Settings > Privacy & security > Screen recording and confirm Microsoft Teams is allowed to share your screen.",
            "If the shared screen appears black to others, try sharing a specific app window instead of the entire desktop.",
            "If screen sharing is unavailable, check with your IT admin — it may be disabled by policy for guest or external users in your organization.",
        ),
    },
    {
        "id": "teams_calendar_sync",
        "service": "teams",
        "intent": "sync",
        "title": "Teams calendar not showing Outlook meetings",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "teams", "calendar", "outlook", "meetings not showing",
            "calendar sync", "sync", "meetings missing", "not syncing",
            "calendar not loading", "teams calendar", "outlook meetings",
            "event", "teems", "calender", "calander", "outlook calendar",
            "calendar not showing", "meetings not appearing",
            "dont show", "meetin", "invite not showing", "not appearing",
        ),
        "steps": (
            "Teams calendar pulls from your Outlook and Exchange calendar — confirm the same account is connected in both apps.",
            "Sign out of Teams and sign back in to force a fresh calendar sync.",
            "Check Outlook to confirm the meeting exists there — if it is missing from Outlook it will not appear in Teams.",
            "If the Teams calendar tab shows a loading spinner, check your computer's date and time settings — a wrong time zone can break calendar sync.",
        ),
    },
    {
        "id": "teams_background_blur",
        "service": "teams",
        "intent": "unknown",
        "title": "Background blur or custom background not available in Teams",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "teams", "background", "blur", "background blur", "custom background",
            "virtual background", "no background option", "background not available",
            "blur not working", "background missing", "replace background",
            "teems", "bakground", "backround", "background effects",
            "video background", "blur my background",
            "greyed out", "setings", "cant find blur", "option greyed",
            "blur option gone", "background option greyed",
        ),
        "steps": (
            "Background blur and custom backgrounds require a compatible camera and GPU — check if your device supports them in Teams Settings > Devices.",
            "During a meeting, click the three dots > Effects and Avatars to find background options.",
            "If the option is greyed out or missing, update the Teams app and your graphics drivers through Windows Update.",
            "As a workaround, enable blur before joining by clicking the blur icon in the camera preview on the pre-join screen.",
        ),
    },
    {
        "id": "teams_performance",
        "service": "teams",
        "intent": "unknown",
        "title": "Teams app slow, freezing, or using high CPU and RAM",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "teams", "slow", "lagging", "lag", "freezing", "frozen",
            "high cpu", "high memory", "lots of ram", "using too much cpu",
            "performance", "sluggish", "not responding", "takes forever",
            "loading slowly", "tems", "teems", "teamss",
            "teams unresponsive", "resource usage", "teams eating cpu",
            "killing", "killing my laptop", "cpu usage", "80 percent",
            "draining", "eating resources", "killing battery",
        ),
        "steps": (
            "Close Teams fully from the system tray by right-clicking the icon and choosing Quit, then reopen it — Teams accumulates memory over long sessions.",
            "Lower video quality during meetings by going to: Settings > Devices > Video and turning on Low bandwidth mode.",
            "Go to: Settings > General and turn on Disable GPU hardware acceleration, then restart Teams — this often reduces CPU usage.",
            "If Teams is still slow, clear the app cache by pressing Windows + R, typing %appdata%\\Microsoft\\Teams, and deleting the contents of the Cache folder.",
        ),
    },
    {
        "id": "teams_file_open",
        "service": "teams",
        "intent": "unknown",
        "title": "Cannot open or download a file shared in Teams",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "teams", "file", "open file", "download", "cant open",
            "cant download", "file shared in teams", "file link",
            "file not opening", "attachment", "download error", "file download",
            "file wont open", "tems", "teems", "flie", "fiel",
            "teams file", "shared file", "download failed",
            "permision", "dont have permision", "cant open it",
            "no permission to open", "says no permission", "file denied",
        ),
        "steps": (
            "Click the file and choose Open in Browser instead of Open in Teams — this uses your browser and avoids app permission issues.",
            "Try downloading the file first, then open it from your Downloads folder.",
            "If the link says you do not have permission, the file may be in a SharePoint library you cannot access — ask the sender to reshare it directly to you.",
            "If all file downloads fail in Teams, go to: Settings > Files and confirm the default storage location is set correctly, then restart Teams.",
        ),
    },
    # ----------------------------------------------------------------- ONEDRIVE
    {
        "id": "onedrive_startup_sync",
        "service": "onedrive",
        "intent": "sync",
        "title": "OneDrive not starting or not syncing on startup",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "onedrive", "not starting", "not syncing", "startup",
            "wont start", "doesnt start", "sync not starting",
            "onedrive missing", "onedrive gone", "cloud icon missing",
            "onedrive not running", "ondrive", "onedrvie", "one drive",
            "not launching", "system tray", "taskbar icon missing",
            "icon gone", "taskbar icon", "gone from tray",
            "tray icon missing", "onedrive icon gone", "disappeared from tray",
        ),
        "steps": (
            "Look for the OneDrive cloud icon in the system tray at the bottom right — if it is not there, search for OneDrive in the Start menu and open it.",
            "Go to: Settings > Apps > Startup and make sure Microsoft OneDrive is set to On.",
            "Inside the OneDrive app, go to Settings > Settings tab and check Start OneDrive automatically when I sign in to Windows.",
            "If OneDrive was accidentally unlinked, click the cloud icon and sign in with your Microsoft account to reconnect it.",
        ),
    },
    {
        "id": "onedrive_online_only",
        "service": "onedrive",
        "intent": "sync",
        "title": "OneDrive files showing as online-only instead of available offline",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "onedrive", "online only", "cloud icon", "files not available offline",
            "always available", "make available offline", "offline files",
            "blue cloud", "white cloud", "cant open file offline",
            "no internet file", "ondrive", "onedrvie", "one drive",
            "online-only", "download to device", "always keep on device",
            "file not avalable", "avalable", "not available offline",
            "cloud only", "shows cloud icon", "not available",
        ),
        "steps": (
            "Right-click the file or folder in File Explorer and choose Always keep on this device — this downloads it for offline access.",
            "To make all OneDrive files available offline, right-click the OneDrive folder in File Explorer, go to Settings, and check the option to keep all files available.",
            "To free up space, right-click any file and choose Free up space to return it to cloud-only without deleting it.",
            "If files revert to online-only automatically, check OneDrive settings to see whether Files On-Demand is configured to cloud-only.",
        ),
    },
    {
        "id": "onedrive_disk_space",
        "service": "onedrive",
        "intent": "unknown",
        "title": "OneDrive taking up too much disk space",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "onedrive", "disk space", "storage", "too much space", "full",
            "hard drive full", "taking up space", "free up space", "low storage",
            "drive almost full", "ondrive", "onedrvie", "one drive",
            "storage full", "not enough space", "disk full", "space used up",
            "almost full", "storage almost full", "eating my drive",
            "eating up", "c drive full", "barely any files",
        ),
        "steps": (
            "In File Explorer, right-click the OneDrive folder and choose Free up space — this converts local copies back to online-only files without deleting them.",
            "Right-click individual large files and choose Free up space to reclaim disk space for files you do not use often.",
            "Go to the OneDrive system tray icon > Settings > Account > Choose folders and uncheck folders you do not need available offline.",
            "Check your cloud storage at onedrive.live.com — if the cloud quota is also full, delete old files or upgrade your storage plan.",
        ),
    },
    {
        "id": "onedrive_conflict_copies",
        "service": "onedrive",
        "intent": "sync",
        "title": "Conflict copies appearing alongside original files in OneDrive",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "onedrive", "conflict", "conflict copy", "duplicate file",
            "two versions", "conflicting copy", "extra copy", "file copy",
            "same file twice", "ondrive", "onedrvie", "one drive",
            "conflcit", "conflit copy", "duplicate", "version conflict",
            "competing edit", "old version",
            "conflcit copy", "copy files", "after working offline",
            "50 conflict", "conflict files everywhere", "two of everything",
        ),
        "steps": (
            "Conflict copies are created when the same file was edited on two devices at the same time — open both versions, compare them, and keep the one you want.",
            "Delete the conflict copy you do not need by right-clicking it and choosing Delete — this only removes the duplicate, not the original.",
            "To prevent future conflicts, close a file on one device before opening it on another, especially when working offline.",
            "If conflicts keep appearing for a specific file, check whether another app or automation is also writing to that same file.",
        ),
    },
    {
        "id": "onedrive_share_link",
        "service": "onedrive",
        "intent": "permissions",
        "title": "Cannot share a OneDrive file or shared link says no access",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "onedrive", "share", "link", "sharing", "cant share", "share link",
            "shared link", "link not working", "no access", "access denied",
            "permission", "link says no access", "generate link", "share file",
            "ondrive", "onedrvie", "one drive", "sharig", "shairng",
            "link expired", "link broken",
            "no acess", "acess", "she cant access", "client cant access",
            "shared link no access", "tells her no access",
        ),
        "steps": (
            "Right-click the file in File Explorer > Share > Copy link and make sure the link permission is set to Anyone with the link or the specific person you are sharing with.",
            "Click the gear icon in the share dialog and confirm Can view or Can edit is selected, not Restricted.",
            "If the link says no access, the file may have been moved or the link revoked — generate a new link.",
            "For files in a SharePoint library, sharing may be restricted by your organization — ask your IT admin if external sharing is disabled.",
        ),
    },
    {
        "id": "onedrive_paused",
        "service": "onedrive",
        "intent": "sync",
        "title": "OneDrive paused due to battery saver or metered connection",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "onedrive", "paused", "sync paused", "battery saver", "metered connection",
            "battery", "low battery", "wifi", "syncing paused", "on pause",
            "ondrive", "onedrvie", "one drive", "not syncing", "sync stopped",
            "battery mode", "data saver", "limited connection", "pause sync",
            "sycn", "pauseing", "bettery", "bettery mode", "baterry",
            "wont sync", "keeps pausing", "pausing sync",
            "bettery saver", "paused in battery", "battery saver mode",
        ),
        "steps": (
            "Click the OneDrive cloud icon in the system tray and click Resume syncing if that option appears.",
            "If you are on battery, go to: Settings > System > Battery and turn off Battery saver — OneDrive pauses automatically when this mode is active.",
            "If you are on a metered Wi-Fi connection, go to OneDrive settings and turn off the option to pause sync on metered connections.",
            "After resuming, click the OneDrive icon and look for red X icons or error messages to check for any files that still need attention.",
        ),
    },
    {
        "id": "onedrive_deleted_file",
        "service": "onedrive",
        "intent": "unknown",
        "title": "File deleted from OneDrive and needs to be recovered",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "onedrive", "deleted", "deleted file", "recover", "restore",
            "file gone", "file missing", "deleted by mistake",
            "accidentally deleted", "restore file", "recycle bin",
            "ondrive", "onedrvie", "one drive", "deleated", "deletd",
            "recovery", "file recovery", "removed file", "undelete",
        ),
        "steps": (
            "Go to onedrive.live.com in a browser, click Recycle bin on the left sidebar — deleted files are kept there for up to 30 days.",
            "Right-click the file in the Recycle bin and choose Restore to put it back in its original location.",
            "In File Explorer, if you just deleted the file moments ago, press Ctrl + Z to undo the deletion.",
            "If the file is not in the Recycle bin and was deleted more than 30 days ago, it cannot be recovered unless your IT admin has backup or retention policies set up.",
        ),
    },
    # --------------------------------------------------------------- SHAREPOINT
    {
        "id": "sharepoint_link_permission",
        "service": "sharepoint",
        "intent": "permissions",
        "title": "SharePoint link says you need permission to access this",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "sharepoint", "share point", "link", "permission", "need permission",
            "request access", "access request", "link not working",
            "sharepoiint", "sharepiont", "shaepoint", "dont have permission",
            "need access", "permission denied", "requesting access",
            "access this page", "cant open link", "no permission",
            "request acess", "acess from", "need to request",
            "says request access", "request permission", "access from owner",
        ),
        "steps": (
            "Make sure you are signed in with the correct Microsoft account — if you have multiple accounts, your browser may be using the wrong one.",
            "Try opening the link in an InPrivate or Incognito window and sign in fresh — this rules out cached credential issues.",
            "If you still get the permission error, click Request access on the page and add a short note explaining why you need access.",
            "If you are the site owner and someone else cannot access it, go to the SharePoint site > Site settings > Site permissions and add them.",
        ),
    },
    {
        "id": "sharepoint_readonly",
        "service": "sharepoint",
        "intent": "unknown",
        "title": "SharePoint document opens as read-only and cannot be edited",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "sharepoint", "read only", "cant edit", "locked", "editing locked",
            "view only", "cant make changes", "document locked", "file locked",
            "sharepoiint", "sharepiont", "read-only", "document not editable",
            "editing not available", "check out", "checked out",
            "no edit button",
            "permision", "wont let me edit", "wont edit", "cant make edits",
            "stuck as read only", "read only mode",
        ),
        "steps": (
            "If someone else has the file open, you may need to wait — Word and SharePoint lock files for editing when another user has them open.",
            "Check if the document is checked out — go to the file in SharePoint, click the three dots, and look for Check in or Check out status.",
            "If the file is checked out to you, open it and click Check In from the ribbon, or check it in directly from SharePoint.",
            "If read-only is due to permissions, ask the SharePoint site owner to grant you Edit or Contribute access to that document library.",
        ),
    },
    {
        "id": "sharepoint_page_load",
        "service": "sharepoint",
        "intent": "unknown",
        "title": "SharePoint page not loading or stuck spinning",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "sharepoint", "not loading", "stuck", "spinning", "loading",
            "slow", "page not loading", "wont load", "site not loading",
            "sharepoiint", "sharepiont", "shaepoint", "blank page",
            "page blank", "keep loading", "spinning wheel",
            "refresh not working", "sharepoint slow",
            "never loads", "site down", "spins forever", "always spinning",
            "spins and never loads", "down for everyone",
        ),
        "steps": (
            "Press Ctrl + F5 to do a hard refresh — this clears the browser's cached version of the page.",
            "Try opening the SharePoint site in a different browser or in a private browsing window to rule out extension or cache conflicts.",
            "Clear your browser's cookies and cached data for sharepoint.com and then sign in again.",
            "If the issue affects everyone in your team, check whether Microsoft 365 has a known outage by searching for Microsoft service health.",
        ),
    },
    {
        "id": "sharepoint_version_history",
        "service": "sharepoint",
        "intent": "unknown",
        "title": "Version history not showing or missing for a SharePoint file",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "sharepoint", "version history", "versions", "previous version",
            "restore version", "file history", "old version",
            "cant see versions", "version not showing", "sharepoiint",
            "sharepiont", "restore old", "undo changes", "file versions",
            "versoin history", "versoin", "recover version",
        ),
        "steps": (
            "In SharePoint, click the three dots next to the file name and choose Version history — this shows all saved versions.",
            "Click any version number to view or restore it — choose Restore to make that version the current one.",
            "If version history is empty or greyed out, versioning may not be enabled — go to Library Settings > Versioning settings and turn it on.",
            "Each library has a maximum number of stored versions — if it is full, the oldest versions are deleted automatically unless an admin increased the limit.",
        ),
    },
    {
        "id": "sharepoint_upload_blocked",
        "service": "sharepoint",
        "intent": "unknown",
        "title": "Cannot upload a file to SharePoint due to size limit or blocked file type",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "sharepoint", "upload", "blocked", "cant upload", "file too large",
            "size limit", "file type", "file blocked", "restricted file",
            "upload error", "sharepoiint", "sharepiont", "file size",
            "too big", "not allowed", "file type not allowed",
            "extension blocked", "uplod",
        ),
        "steps": (
            "If the file is very large (over 250 MB), try compressing it or splitting it into smaller parts before uploading.",
            "Some file types such as .exe and scripts are blocked by default — zip the file or rename the extension if the content is safe.",
            "If the error mentions special characters, remove symbols like # % & { } \\ / * from the file name and try again.",
            "If a specific file type is blocked by your organization's policy, ask your IT admin to allow it or use an alternative format.",
        ),
    },
    # ---------------------------------------------------------- WINDOWS/GENERAL
    {
        "id": "windows_hello_login",
        "service": "windows",
        "intent": "sign_in",
        "title": "Windows Hello, fingerprint, or PIN not working at login",
        "source": "Local Windows support playbook",
        "keywords": (
            "windows", "hello", "fingerprint", "pin", "face recognition",
            "biometric", "login", "cant log in", "sign in", "login not working",
            "pin not working", "fingerprint not working", "windwos", "widnows",
            "wndows", "pin error", "hello error", "cant unlock",
            "biometrics",
            "figner print", "figner", "stopped workin", "wont recognize",
            "after update", "not recognizing", "finger print stopped",
        ),
        "steps": (
            "If your PIN or fingerprint is rejected, try signing in with your full Microsoft account password — this always works as a fallback.",
            "Go to: Settings > Accounts > Sign-in options, remove your current PIN or fingerprint, and set it up again fresh.",
            "If Windows Hello says it cannot be set up, go to: Settings > Windows Update and install any pending updates — a driver update may be needed.",
            "For fingerprint issues, clean the sensor with a dry cloth and re-enroll using a different angle or a different finger.",
        ),
    },
    {
        "id": "windows_wifi_no_internet",
        "service": "windows",
        "intent": "unknown",
        "title": "Wi-Fi shows connected but there is no internet access",
        "source": "Local Windows support playbook",
        "keywords": (
            "windows", "wifi", "wi-fi", "connected", "no internet",
            "internet not working", "connected but no internet",
            "browser not loading", "cant browse", "pages not loading",
            "limited", "no access", "windwos", "widnows", "wfi", "wiifi",
            "no internet access", "limited connectivity", "internet dropped",
            "internet not workin", "webpages wont load", "cant browse web",
            "pages wont load", "no webpages", "connected full bars",
        ),
        "steps": (
            "Disconnect from the Wi-Fi network and reconnect — click the Wi-Fi icon in the taskbar, select your network, disconnect, then reconnect.",
            "Right-click the Wi-Fi icon in the taskbar and choose Troubleshoot problems — Windows can often repair the connection automatically.",
            "Open a browser and try a simple site — if one site loads but others do not, the issue may be a specific site, not your connection.",
            "Restart your router or switch to a mobile hotspot to test — if mobile data works fine, the issue is the local network and not your computer.",
        ),
    },
    {
        "id": "windows_update_stuck",
        "service": "windows",
        "intent": "unknown",
        "title": "Windows update stuck, failing, or showing an error code",
        "source": "Local Windows support playbook",
        "keywords": (
            "windows", "update", "stuck", "failing", "error", "wont update",
            "update error", "cant install update", "update loop",
            "windwos", "widnows", "wndows", "windows update", "updaet",
            "updat", "update failed", "stuck at percent",
            "update not installing", "error code",
            "updaet stuck", "force restart", "stuck installing",
            "stuck at 94", "been hours", "safe to restart",
        ),
        "steps": (
            "Restart your computer — many update failures clear after a restart and Windows will retry automatically.",
            "Go to: Settings > Windows Update and click Check for updates to refresh the update queue and clear a stalled download.",
            "If a specific error code appears, note it and search for that exact code at support.microsoft.com for targeted guidance.",
            "If updates keep failing, run the Windows Update Troubleshooter from: Settings > System > Troubleshoot > Other troubleshooters.",
        ),
    },
    {
        "id": "windows_slow_after_update",
        "service": "windows",
        "intent": "unknown",
        "title": "PC running slowly or lagging after a recent Windows update",
        "source": "Local Windows support playbook",
        "keywords": (
            "windows", "slow", "lagging", "sluggish", "update",
            "after update", "slower", "pc slow", "computer slow",
            "windwos", "widnows", "wndows", "performance", "slow pc",
            "slow computer", "lagging after update",
            "ran update now slow", "update made computer slow",
            "trippin", "super slow", "after the update", "running slow",
            "everything slow", "acting up", "slow after the update",
            "updaet", "pc", "after the updaet", "runs slow",
            "completely unusable", "freezes", "everything freezes",
        ),
        "steps": (
            "Restart your computer if you have not done so since the update — some updates fully apply only on a fresh reboot.",
            "After restarting, let the computer sit idle for 15 minutes — Windows often runs background indexing and cleanup tasks that temporarily slow things down.",
            "Press Ctrl + Shift + Esc to open Task Manager and look for any process using high CPU or disk — this helps identify what is running.",
            "If the slowness persists after an hour, roll back the update by going to: Settings > Windows Update > Update history > Uninstall updates.",
        ),
    },
    {
        "id": "windows_start_taskbar",
        "service": "windows",
        "intent": "crash",
        "title": "Start menu or taskbar not opening or not responding",
        "source": "Local Windows support playbook",
        "keywords": (
            "windows", "start menu", "taskbar", "not opening", "not responding",
            "frozen", "dead", "click not working", "start button broken",
            "search bar", "taskbar frozen", "windwos", "widnows",
            "start manu", "tasbar", "tskbar", "start menu broken",
            "taskbar not working", "desktop frozen",
            "stopped respondin", "cant open start", "wont open",
            "start button stopped", "taskbar stopped", "both stopped",
        ),
        "steps": (
            "Press Ctrl + Alt + Delete and choose Sign out, then sign back in — this refreshes the Windows shell without a full restart.",
            "Right-click the taskbar and check if the right-click menu opens — if it does, your taskbar is partially working and a restart may fix the rest.",
            "Restart Windows Explorer by pressing Ctrl + Shift + Esc, find Windows Explorer in the list, right-click it, and choose Restart.",
            "If the issue comes back after updates, go to: Settings > Windows Update > Advanced options and pause updates temporarily to confirm whether the update is the cause.",
        ),
    },
    {
        "id": "windows_shutdown_slow",
        "service": "windows",
        "intent": "unknown",
        "title": "Windows not shutting down or taking forever to restart",
        "source": "Local Windows support playbook",
        "keywords": (
            "windows", "shutdown", "restart", "slow shutdown", "taking forever",
            "wont shut down", "hanging", "stuck on shutdown", "restart slow",
            "windwos", "widnows", "shtudown", "shtdown", "restrat",
            "shutting down screen", "stuck on restarting",
            "computer wont turn off",
            "hangs", "slow to shutdown", "just hangs",
            "10 mins to shutdown", "takes forever to shut", "hangs on shutdown",
        ),
        "steps": (
            "Wait at least two minutes before force-shutting down — some updates install silently during shutdown and cutting power can corrupt the system.",
            "If it is safe to do so, hold the power button for 10 seconds to force a shutdown, then power it back on and let Windows finish any pending tasks.",
            "Check for pending Windows updates in Settings > Windows Update — an update waiting to finalize can cause very slow shutdowns.",
            "If slow shutdowns happen regularly, search for Event Viewer in the Start menu and look under Windows Logs > System for shutdown errors.",
        ),
    },
    {
        "id": "windows_keyboard_layout",
        "service": "windows",
        "intent": "unknown",
        "title": "Keyboard layout or language changed unexpectedly",
        "source": "Local Windows support playbook",
        "keywords": (
            "windows", "keyboard", "layout", "language", "changed",
            "wrong language", "keyboard changed", "wrong layout",
            "typing wrong", "shortcuts changed", "windwos", "widnows",
            "keybord", "keyborad", "language switched",
            "accidental keyboard switch", "keyboard language", "input method",
            "keybord switched", "switched layout", "keys wrong", "wrong keys",
            "keys r wrong", "layout changed", "symbols wrong",
        ),
        "steps": (
            "Press Windows + Space to cycle through your installed keyboard layouts and switch back to the correct one.",
            "Go to: Settings > Time & language > Language & region and remove any keyboard layouts you did not intentionally add.",
            "If the layout keeps switching on its own, you may be accidentally pressing the layout shortcut — Windows uses Ctrl + Shift or Alt + Shift to switch layouts by default.",
            "To disable the layout switching shortcut, go to: Settings > Time & language > Typing > Advanced keyboard settings > Input language hot keys and set it to Not assigned.",
        ),
    },
    {
        "id": "windows_copy_paste",
        "service": "windows",
        "intent": "unknown",
        "title": "Copy and paste not working in any app",
        "source": "Local Windows support playbook",
        "keywords": (
            "windows", "copy", "paste", "copy paste", "ctrl c", "ctrl v",
            "not working", "cant copy", "cant paste", "copy paste broken",
            "clipboard", "windwos", "widnows", "coppy", "cpoy",
            "paste not working", "ctrl+c", "ctrl+v",
            "clipboard empty", "clipboard not working",
        ),
        "steps": (
            "Try using the right-click menu to Copy and Paste instead of keyboard shortcuts — this confirms whether the issue is with the keyboard or the clipboard itself.",
            "Restart the app you are copying from and the one you are pasting into — a frozen app can block the clipboard for everything else.",
            "Press Windows + V to open Clipboard history — if items appear there, the clipboard is working and the issue is with the destination app.",
            "If copy-paste is broken everywhere, press Ctrl + Shift + Esc, find rdpclip.exe in the process list, end it, then try again.",
        ),
    },
    {
        "id": "windows_app_install_blocked",
        "service": "windows",
        "intent": "permissions",
        "title": "Cannot install an app blocked by policy or missing admin rights",
        "source": "Local Windows support playbook",
        "keywords": (
            "windows", "install", "blocked", "cant install", "not allowed",
            "policy", "admin", "administrator", "app blocked",
            "needs administrator", "organization", "company blocked",
            "windwos", "widnows", "instal", "installl",
            "app wont install", "blocked by policy", "requires admin",
            "permission to install",
        ),
        "steps": (
            "Right-click the installer and choose Run as administrator — some apps require elevated permissions to install.",
            "If a policy message appears saying the app is blocked, check with your IT admin — they control what software can be installed on managed company devices.",
            "For apps from the Microsoft Store, check that the Store is not restricted — open Microsoft Store and try downloading from there instead.",
            "If you are an admin on your own device, go to: Settings > Apps > Advanced app settings and change the installer permission to Anywhere.",
        ),
    },
    {
        "id": "windows_clock_wrong",
        "service": "windows",
        "intent": "unknown",
        "title": "System clock showing wrong time or date",
        "source": "Local Windows support playbook",
        "keywords": (
            "windows", "clock", "time", "date", "wrong time", "wrong date",
            "time off", "clock wrong", "time not syncing", "windwos", "widnows",
            "cloock", "dat", "time incorrect", "time zone",
            "incorrect time", "system time", "internet time", "ntp",
        ),
        "steps": (
            "Right-click the clock in the taskbar, choose Adjust date/time, and turn on both Set time automatically and Set time zone automatically.",
            "If the time is slightly off, click Sync now in the same settings to force an immediate sync with the internet time server.",
            "If the time zone is wrong, turn off Set time zone automatically and manually choose your correct time zone from the list.",
            "If the clock keeps drifting back to the wrong time after syncing, the CMOS battery inside your computer may need replacing — this requires a technician.",
        ),
    },
    {
        "id": "windows_audio_switch",
        "service": "windows",
        "intent": "audio",
        "title": "Headphone or speaker not switching when plugged in",
        "source": "Local Windows support playbook",
        "keywords": (
            "windows", "headphones", "headphone", "speaker", "speakers",
            "not switching", "wont switch", "audio not switching",
            "sound still from speakers", "still playing from laptop",
            "plug in headphones", "windwos", "widnows", "heaphones",
            "speker", "audio output", "jack", "3.5mm",
            "sound device", "default audio",
        ),
        "steps": (
            "Plug in your headphones and right-click the speaker icon in the taskbar, then choose Sound settings to check if they appear as an output option.",
            "In Sound settings, under Output, manually select your headphones if Windows did not switch automatically.",
            "Right-click the speaker icon > Sound settings > More sound settings > Playback tab, right-click your headphones, and choose Set as Default Device.",
            "If headphones appear in Device Manager but not in Sound settings, right-click an empty area of the Playback tab and choose Show Disabled Devices, then enable them.",
        ),
    },
    # ----------------------------------------------- MICROSOFT ACCOUNT/SIGN-IN
    {
        "id": "microsoft_account_2fa_code",
        "service": "microsoft account",
        "intent": "sign_in",
        "title": "Two-factor authentication code not arriving by text or email",
        "source": "Local Microsoft account support playbook",
        "keywords": (
            "microsoft account", "two factor", "2fa", "mfa",
            "verification code", "code not arriving", "code not sent",
            "security code", "not getting code", "sms code",
            "text message code", "micorsoft", "microsft",
            "authenticaion", "two-factor", "backup code",
            "verification not working", "code by text",
            "authenicator", "acct", "txt code", "isnt working",
            "cant get code", "signing in", "microsoft acct",
        ),
        "steps": (
            "Check that the phone number and backup email on file are correct by going to account.microsoft.com > Security > Advanced security options.",
            "If the text code is not arriving, wait 60 seconds and request a new one — codes expire quickly and carriers sometimes delay SMS.",
            "On the sign-in screen, choose a different verification method such as the Authenticator app or a backup email code.",
            "If no method works and you are locked out, go to account.microsoft.com/recover and provide as much identity information as you can.",
        ),
    },
    {
        "id": "microsoft_account_locked_out",
        "service": "microsoft account",
        "intent": "sign_in",
        "title": "Locked out of Microsoft account with no recovery options available",
        "source": "Local Microsoft account support playbook",
        "keywords": (
            "microsoft account", "locked out", "no recovery", "cant recover",
            "lost access", "account recovery", "cant sign in",
            "lost phone", "lost email", "recovery code", "micorsoft",
            "microsft", "acount locked", "no backup", "locked account",
            "recovery options", "account access", "verify identity",
            "lokced out", "lokced", "completely locked out",
            "lost access to phone", "no backup email", "cant get back in",
        ),
        "steps": (
            "Go to account.microsoft.com/recover and submit a recovery request — Microsoft will ask identity questions to verify the account belongs to you.",
            "Fill in as much detail as possible — previous passwords, account creation date, and devices you signed in from all improve your chances.",
            "If you had an Authenticator app on a lost phone, you can still try recovery — Microsoft may take 24 to 72 hours to respond.",
            "Once you regain access, add at least two backup verification methods so you are not locked out again in the future.",
        ),
    },
    {
        "id": "microsoft_account_authenticator",
        "service": "microsoft account",
        "intent": "sign_in",
        "title": "Microsoft Authenticator app not showing codes or not working",
        "source": "Local Microsoft account support playbook",
        "keywords": (
            "microsoft authenticator", "authenticator", "codes not showing",
            "not working", "cant use authenticator", "authenticator app",
            "blank", "no codes", "push notification", "approve request",
            "micorsoft", "microsft", "authinticator", "authentcator",
            "mfa app", "authenticator broken", "not getting push notification",
            "shows nothing", "new phone", "switched phones",
            "new iphone", "shows blank", "no codes showing",
        ),
        "steps": (
            "Open the Authenticator app and check that your account tile is visible — swipe down to refresh or tap the tile to generate a fresh code.",
            "Make sure your phone's date and time are set automatically — Authenticator codes stop working if the phone time is even a few minutes off.",
            "If push approval notifications are not arriving, check that the Authenticator app has notification permission in your phone's app settings.",
            "If you changed phones, re-enroll Authenticator by signing in at mysignins.microsoft.com > Security info > Add method > Authenticator app.",
        ),
    },
    {
        "id": "microsoft_account_password_reset",
        "service": "microsoft account",
        "intent": "password_reset",
        "title": "Cannot change or reset Microsoft account password",
        "source": "Local Microsoft account support playbook",
        "keywords": (
            "microsoft account", "password reset", "change password",
            "forgot password", "reset password", "cant reset",
            "micorsoft", "microsft", "pasword", "passord",
            "password not resetting", "reset not working", "account password",
            "reset link", "recovery email", "password change",
            "old password not working",
            "errors out", "button not working", "cant save password",
            "page errors", "reset page broken", "change password errors",
        ),
        "steps": (
            "Go to account.microsoft.com and click Change password — you will need to know your current password to change it this way.",
            "If you forgot your password, click Forgot password on the Microsoft sign-in page and follow the steps to verify your identity.",
            "If the reset email or text is not arriving, check your spam folder and make sure the recovery contact on file is still one you can access.",
            "After resetting, sign out of all devices and apps and sign back in with the new password — Outlook and other apps will prompt for the new credentials.",
        ),
    },
    # -------------------------------------------------------- MICROSOFT 365 APPS
    {
        "id": "office_activation_prompt",
        "service": "microsoft 365",
        "intent": "sign_in",
        "title": "Office apps asking to activate even though subscription is active",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "office", "microsoft 365", "activation", "activate",
            "asking to activate", "subscription", "product key",
            "unlicensed product", "office not activated", "sign in to activate",
            "word", "excel", "powerpoint", "activaion", "actiation",
            "office license", "subscription active", "already paid",
            "activiate", "m365", "tellin me to activate", "keeps asking to activate",
            "activate even though", "pay every month", "paid subscription",
        ),
        "steps": (
            "Open any Office app, go to: File > Account, and sign in with the Microsoft account that holds your active subscription.",
            "If you are already signed in but still see the prompt, click Activate Product and sign in again — a re-authentication often clears the licensing check.",
            "Go to microsoft365.com and confirm your subscription is active and assigned to the same account you are using in Office.",
            "If it still shows as unlicensed after signing in, try signing out of Office under File > Account > Sign Out, then sign back in.",
        ),
    },
    {
        "id": "office_immediate_crash",
        "service": "microsoft 365",
        "intent": "crash",
        "title": "Word, Excel, or PowerPoint crashes immediately on open",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "word", "excel", "powerpoint", "crashes", "crash on open",
            "crashes immediately", "wont open", "opens then closes",
            "instant crash", "keeps crashing", "office crash",
            "microsoft 365", "offce", "exel", "wrd", "powerpint",
            "opening crash", "launch crash", "crashes on startup",
            "dying", "keeps dying", "instantly crashes", "immediately crashes",
            "wont stay open", "crashes when i open",
            "dies", "instantly", "right away", "addin", "profle", "crash right away",
            "dies instantly", "every pc", "all computers",
        ),
        "steps": (
            "Hold Ctrl while clicking the app icon to open it in Safe Mode — if it opens in Safe Mode, an add-in is likely causing the crash.",
            "Disable add-ins by going to: File > Options > Add-ins > Manage: COM Add-ins > Go, uncheck all add-ins, and restart the app.",
            "Run an Office Quick Repair by going to: Settings > Apps > find Microsoft 365 > Modify > Quick Repair — this fixes corrupted files without reinstalling.",
            "If crashes only happen with one specific file, copy the content into a blank new document as a workaround while the original is repaired.",
        ),
    },
    {
        "id": "office_save_permission",
        "service": "microsoft 365",
        "intent": "permissions",
        "title": "Cannot save an Office file due to permission error or read-only mode",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "word", "excel", "powerpoint", "office", "save", "cant save",
            "permission", "read only", "save error", "read-only",
            "permission error", "offce", "exel", "wrd", "file locked",
            "save failed", "document locked", "cant edit",
            "save as", "save blocked", "file permission",
            "permision", "gettin error", "cant save here",
            "permission to save", "save location error", "no permission to save",
        ),
        "steps": (
            "Use Save As and save the file to your Desktop or Documents folder instead of the original location — this works around a folder permission issue.",
            "If the file shows a yellow Protected View bar at the top, click Enable Editing to turn off read-only mode.",
            "Right-click the saved file, choose Properties, and uncheck the Read-only attribute at the bottom if it is checked.",
            "If you are saving to OneDrive or a network drive and get a permission error, save locally to Desktop first, then copy the file to the destination.",
        ),
    },
    {
        "id": "office_autosave_off",
        "service": "microsoft 365",
        "intent": "unknown",
        "title": "AutoSave keeps turning off or will not stay enabled in Office",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "office", "word", "excel", "powerpoint", "autosave", "auto save",
            "auto-save", "turning off", "won't stay on",
            "not saving automatically", "autosave off", "autosave not working",
            "lose changes", "lost work", "offce", "exel", "wrd",
            "autosave disabled", "autosave keep off", "autosave greyed out",
            "turnin off", "switching off", "greyed out", "toggle",
            "keeps turning off", "autosave toggle", "cant turn on autosave",
        ),
        "steps": (
            "AutoSave only works for files stored in OneDrive or SharePoint — if your file is saved locally, the AutoSave toggle will remain grey.",
            "Move your file to OneDrive by clicking File > Save As > OneDrive, then the AutoSave toggle at the top left should turn on automatically.",
            "If AutoSave is available but keeps turning off, check whether Protected View or Compatibility Mode is active — both can disable AutoSave.",
            "You can always save manually with Ctrl + S at any time — this works regardless of where the file is stored.",
        ),
    },
    {
        "id": "office_spellcheck",
        "service": "microsoft 365",
        "intent": "unknown",
        "title": "Spell check not working or not catching errors in Office",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "word", "excel", "powerpoint", "office", "spell check", "spellcheck",
            "not working", "no red underlines", "spelling", "autocorrect",
            "spell checker", "grammar", "offce", "exel", "wrd",
            "spel check", "spellchek", "typos not caught",
            "words not underlined", "check spelling", "proofing",
            "stopped workin", "no red lines", "typos", "not catching",
            "obvious typos", "red lines gone", "spell check off",
        ),
        "steps": (
            "Go to: File > Options > Proofing and make sure Check spelling as you type is checked.",
            "Confirm the document language is correct by going to: Review > Language > Set Proofing Language and matching it to the language you are typing in.",
            "If spell check is off for a specific section, select all text with Ctrl + A, go to: Review > Language > Set Proofing Language, and uncheck Do not check spelling or grammar.",
            "If none of that helps, run a Quick Repair by going to: Settings > Apps > Microsoft 365 > Modify > Quick Repair.",
        ),
    },
    {
        "id": "office_recent_files",
        "service": "microsoft 365",
        "intent": "unknown",
        "title": "Recent files list empty or not showing in Office apps",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "word", "excel", "powerpoint", "office", "recent files", "recent",
            "not showing", "empty", "missing", "recent documents",
            "recent list", "file history", "offce", "exel", "wrd",
            "recnt files", "recnet", "pinned files",
            "quick access", "recently opened",
            "vanished", "list is empty", "list empty",
            "recent list empty", "recnt", "files vanished",
        ),
        "steps": (
            "Open any Office app and go to: File > Open > Recent to confirm whether the list is empty there rather than just on the Start screen.",
            "Go to: File > Options > Advanced > Display and make sure Show this number of Recent Documents is set to a number greater than 0.",
            "Pin important files by clicking the thumbtack icon next to them in the recent list — pinned files persist even if the list is cleared.",
            "If the recent list was cleared by an update, the files are still on your computer — open them normally and they will reappear in the recent list as you use them.",
        ),
    },
)
