ADDITIONAL_KNOWLEDGE_RESOURCES = (
    # --------------------------------------------------------------- OUTLOOK
    {
        "id": "outlook_work_offline_send_receive",
        "service": "outlook",
        "intent": "email_delivery",
        "title": "Outlook is in Work Offline mode and mail will not send",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "outlook", "email", "mail", "send", "sending", "not sending",
            "work offline", "offline mode", "disconnected", "trying to connect",
            "outbox", "send receive", "send/receive", "mail stuck",
            "still not sending", "not going out",
        ),
        "steps": (
            "In Outlook, open the Send/Receive tab and make sure Work Offline is not selected.",
            "Check the status bar at the bottom of Outlook for Offline, Disconnected, or Trying to connect.",
            "Open Outlook on the web and send a short test email to confirm the account can send outside the desktop app.",
            "If webmail sends but desktop Outlook does not, restart Outlook and reconnect the account before retrying the Outbox item.",
        ),
    },
    {
        "id": "outlook_mailbox_full",
        "service": "outlook",
        "intent": "email_delivery",
        "title": "Outlook mailbox is full and cannot send or receive mail",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "outlook", "mailbox full", "quota", "storage full", "mailbox quota",
            "cannot send", "can't send", "cant send", "not receiving",
            "mailbox size", "storage limit", "send receive", "mail stuck",
            "recipient says mailbox full",
        ),
        "steps": (
            "In Outlook, go to File > Tools > Mailbox Cleanup and check the mailbox size.",
            "Delete or archive large messages, especially messages with attachments, then empty Deleted Items.",
            "Try sending and receiving again from Outlook on the web to confirm the mailbox is below quota.",
            "If the mailbox is a shared or work mailbox, ask support to confirm the quota and retention policy.",
        ),
    },
    {
        "id": "outlook_rules_misrouting_mail",
        "service": "outlook",
        "intent": "sync",
        "title": "Outlook rules are moving emails to the wrong folder",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "outlook", "rules", "email rules", "mail rules", "missing emails",
            "wrong folder", "moving automatically", "emails disappear",
            "mail disappears", "inbox", "junk", "folder", "redirecting",
        ),
        "steps": (
            "In Outlook, go to File > Manage Rules & Alerts and review active rules.",
            "Temporarily turn off rules that move or delete messages, then send yourself a test email.",
            "Check Junk, Archive, Deleted Items, and any custom folders for the missing messages.",
            "If rules reappear after being disabled, check Outlook on the web rules because server-side rules can override the desktop app.",
        ),
    },
    {
        "id": "outlook_delegated_send_as",
        "service": "outlook",
        "intent": "permissions",
        "title": "Cannot send as or send on behalf of a shared mailbox",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "outlook", "shared mailbox", "send as", "send on behalf",
            "delegate", "delegated", "permission", "not authorized",
            "cannot send from", "can't send from", "cant send from",
            "from field", "shared email",
        ),
        "steps": (
            "In a new message, turn on the From field and choose the shared mailbox address.",
            "If Outlook says you are not authorized, confirm support granted Send As or Send on Behalf permission, not just read access.",
            "Try sending from Outlook on the web after permissions are updated because mailbox permissions can take time to reach desktop Outlook.",
            "If webmail works but desktop Outlook does not, remove and re-add the shared mailbox profile entry.",
        ),
    },
    {
        "id": "outlook_recall_or_delay_send",
        "service": "outlook",
        "intent": "email_delivery",
        "title": "Outlook message recall, delay delivery, or scheduled send problem",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "outlook", "recall message", "message recall", "delay delivery",
            "scheduled send", "send later", "delayed send", "stuck scheduled",
            "did not recall", "recall failed", "defer delivery",
        ),
        "steps": (
            "Check the Outbox and Drafts folders for delayed or scheduled messages that have not actually sent yet.",
            "Open the message options and confirm Delay Delivery is not set to a future time.",
            "For recall, remember it only works in limited Microsoft Exchange scenarios and usually fails if the recipient already opened the email.",
            "If the message must be corrected, send a clear follow-up email rather than relying on recall alone.",
        ),
    },
    # ---------------------------------------------------------------- TEAMS
    {
        "id": "teams_screen_share_permissions",
        "service": "teams",
        "intent": "permissions",
        "title": "Teams screen sharing is blocked or shows a black screen",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "teams", "screen share", "share screen", "sharing screen",
            "black screen", "presentation not showing", "cannot share",
            "can't share", "cant share", "permission", "presenter",
            "share tray", "window not showing", "screen sharing",
            "shows black",
        ),
        "steps": (
            "In the meeting, confirm you have presenter rights and the Share button is available.",
            "Try sharing a single window first, then try sharing the full screen if the window capture stays black.",
            "Close and reopen Teams so it refreshes available windows and display permissions.",
            "If sharing works in Teams on the web, the desktop app cache or graphics driver is the likely path.",
        ),
    },
    {
        "id": "teams_presence_stuck",
        "service": "teams",
        "intent": "sync",
        "title": "Teams presence or status is stuck",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "teams", "status", "presence", "available", "busy", "away",
            "stuck away", "stuck busy", "status stuck", "showing offline",
            "wrong status", "green dot", "red dot",
        ),
        "steps": (
            "Manually change your Teams status once, then set it back to Reset status.",
            "Check whether Outlook has a calendar event currently marking you busy or out of office.",
            "Fully quit Teams from the system tray and reopen it to refresh presence.",
            "If the web app shows the correct status but desktop does not, clear the Teams cache or reinstall Teams.",
        ),
    },
    {
        "id": "teams_call_no_ring",
        "service": "teams",
        "intent": "notification",
        "title": "Teams calls do not ring or call notifications are missed",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "teams", "call", "calls", "not ringing", "does not ring",
            "missed call", "incoming call", "call notification",
            "ringtone", "no sound", "do not disturb", "focus assist",
        ),
        "steps": (
            "In Teams Settings > Notifications, confirm calls are allowed to show banners and play sound.",
            "Check your Teams status and make sure Do not disturb is not enabled.",
            "In Windows Settings > System > Notifications, confirm Teams notifications are allowed.",
            "Make a test call and verify the selected speaker in Teams Settings > Devices.",
        ),
    },
    {
        "id": "teams_files_upload_fail",
        "service": "teams",
        "intent": "sync",
        "title": "Teams file upload fails in a chat or channel",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "teams", "file upload", "upload file", "attachment", "attach file",
            "cannot upload", "can't upload", "cant upload", "upload failed",
            "channel file", "chat file", "file not sending",
        ),
        "steps": (
            "Try uploading the file from Teams on the web to see whether the desktop app is the blocker.",
            "Rename the file to remove special characters and shorten the file path.",
            "If it is a channel file, open the channel Files tab in SharePoint and try uploading there.",
            "If SharePoint also rejects it, the issue is likely permission, file size, or a blocked file type.",
        ),
    },
    {
        "id": "teams_meeting_lobby",
        "service": "teams",
        "intent": "permissions",
        "title": "Teams meeting stuck in lobby or cannot admit attendees",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "teams", "lobby", "waiting in lobby", "stuck in lobby",
            "admit", "cannot admit", "can't admit", "cant admit",
            "meeting options", "who can bypass", "attendee stuck",
        ),
        "steps": (
            "Open Meeting options and check Who can bypass the lobby.",
            "Confirm the person trying to admit attendees is an organizer or presenter.",
            "If the lobby controls do not appear, leave and rejoin the meeting as the organizer account.",
            "For recurring meetings, update the meeting options from the calendar invite so the next occurrence inherits the right settings.",
        ),
    },
    # --------------------------------------------------------------- ONEDRIVE
    {
        "id": "onedrive_red_x_status",
        "service": "onedrive",
        "intent": "sync",
        "title": "OneDrive shows a red X or sync error on files",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "onedrive", "red x", "sync error", "sync errors", "file error",
            "folder error", "not syncing", "sync failed", "cloud icon",
            "red mark", "red circle", "error icon",
        ),
        "steps": (
            "Select the OneDrive cloud icon and open the sync activity panel to see the exact file causing the red X.",
            "Fix file-specific blockers such as invalid characters, long paths, or a file open in another app.",
            "Pause syncing for a minute, then resume syncing after fixing the listed file.",
            "If the same item keeps failing, move it outside OneDrive, rename it, then move it back.",
        ),
    },
    {
        "id": "onedrive_account_mismatch",
        "service": "onedrive",
        "intent": "sign_in",
        "title": "OneDrive is signed into the wrong account",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "onedrive", "wrong account", "different account", "personal account",
            "work account", "account mismatch", "files missing", "not my files",
            "signed into wrong", "business account", "school account",
        ),
        "steps": (
            "Select the OneDrive cloud icon, open Settings > Account, and confirm the email address shown there.",
            "If it is the wrong account, unlink this PC and sign in with the correct work or school account.",
            "After sign-in, choose the expected OneDrive folder location and let it finish indexing before judging missing files.",
            "If both personal and work OneDrive are used, check which cloud icon is active before moving files.",
        ),
    },
    {
        "id": "onedrive_storage_full",
        "service": "onedrive",
        "intent": "sync",
        "title": "OneDrive storage is full and uploads stop",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "onedrive", "storage full", "quota", "out of space",
            "no space", "upload stopped", "cannot upload", "can't upload",
            "cant upload", "storage limit", "cloud storage full",
        ),
        "steps": (
            "Open OneDrive on the web and check storage usage from the settings or storage page.",
            "Delete unneeded large files and empty the OneDrive recycle bin so the quota actually drops.",
            "If this is a work account and the storage looks incorrect, ask support to confirm the assigned OneDrive quota.",
            "After clearing space, restart OneDrive and let pending uploads retry.",
        ),
    },
    {
        "id": "onedrive_files_on_demand",
        "service": "onedrive",
        "intent": "sync",
        "title": "OneDrive file is online-only or not available offline",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "onedrive", "online only", "available offline", "always keep",
            "free up space", "cloud icon", "green check", "not available offline",
            "cannot open offline", "can't open offline", "cant open offline",
        ),
        "steps": (
            "Right-click the file or folder and choose Always keep on this device if you need it offline.",
            "Wait until the status icon changes from a cloud to a green check before disconnecting from the internet.",
            "If the file will not download, check the OneDrive activity panel for a sync or permission error.",
            "Use Free up space only for files you do not need locally because it makes them online-only again.",
        ),
    },
    {
        "id": "onedrive_path_length_invalid_name",
        "service": "onedrive",
        "intent": "sync",
        "title": "OneDrive file name or path is too long or invalid",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "onedrive", "file name", "filename", "path too long",
            "invalid character", "invalid characters", "name too long",
            "cannot sync", "can't sync", "cant sync", "rename file",
            "folder path", "special character",
        ),
        "steps": (
            "Shorten the folder path by moving the file closer to the top of the OneDrive folder.",
            "Rename files and folders to remove special characters such as quotes, asterisks, colons, and trailing spaces.",
            "Pause and resume OneDrive sync after renaming so it rechecks the path.",
            "If many files are affected, fix the top-level folder names first because every nested item inherits that path.",
        ),
    },
    # ------------------------------------------------------------- SHAREPOINT
    {
        "id": "sharepoint_sync_button_missing",
        "service": "sharepoint",
        "intent": "sync",
        "title": "SharePoint Sync button is missing or does nothing",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "sharepoint", "sync button", "sync missing", "button missing",
            "sync does nothing", "sync library", "document library",
            "onedrive prompt", "open in onedrive", "library not syncing",
        ),
        "steps": (
            "Open the SharePoint document library in a browser and confirm you are in the library view, not a single file preview.",
            "Check whether you have permission to sync the library; view-only access may block local sync.",
            "Make sure OneDrive is running and signed into the same work account before pressing Sync.",
            "If the button still does nothing, use Add shortcut to OneDrive as an alternate path.",
        ),
    },
    {
        "id": "sharepoint_required_metadata",
        "service": "sharepoint",
        "intent": "permissions",
        "title": "SharePoint requires metadata before a file can save or upload",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "sharepoint", "metadata", "required column", "required columns",
            "properties", "document information panel", "info panel",
            "cannot save", "can't save", "cant save", "upload blocked",
            "required field", "save", "before save",
        ),
        "steps": (
            "Open the file in the SharePoint browser library and look for missing required properties.",
            "Fill in required columns such as category, owner, status, or department, then save again.",
            "If editing from Word, Excel, or PowerPoint, open File > Info and check for required document properties.",
            "If you do not know the required value, ask the site owner because required metadata is controlled by the library settings.",
        ),
    },
    {
        "id": "sharepoint_checked_out_file",
        "service": "sharepoint",
        "intent": "permissions",
        "title": "SharePoint file is checked out or locked for editing",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "sharepoint", "checked out", "check out", "locked for editing",
            "locked by another user", "cannot edit", "can't edit", "cant edit",
            "read only", "someone else editing", "file locked",
        ),
        "steps": (
            "In the SharePoint library, check the file details to see whether it is checked out or locked by another user.",
            "If you checked it out, check it back in so others can edit it.",
            "If another user has it open, ask them to close the file or check it in.",
            "If the lock is stale, the site owner may need to discard checkout or release the lock.",
        ),
    },
    {
        "id": "sharepoint_restore_deleted_file",
        "service": "sharepoint",
        "intent": "sync",
        "title": "Restore a deleted SharePoint file or folder",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "sharepoint", "deleted file", "deleted folder", "restore file",
            "restore folder", "recycle bin", "missing file", "file disappeared",
            "folder disappeared", "recover", "accidentally deleted",
        ),
        "steps": (
            "Open the SharePoint site in a browser and go to Recycle bin from the left navigation or site contents.",
            "Select the deleted file or folder and choose Restore.",
            "If it is not in the first-stage recycle bin, ask a site owner to check the second-stage recycle bin.",
            "After restoring, refresh any synced OneDrive folder so the restored item appears locally again.",
        ),
    },
    # ------------------------------------------------------- OFFICE DESKTOP APPS
    {
        "id": "word_protected_view_editing",
        "service": "word",
        "intent": "permissions",
        "title": "Word document opens in Protected View or cannot enable editing",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "word", "protected view", "enable editing", "cannot edit",
            "can't edit", "cant edit", "read only", "blocked file",
            "downloaded document", "yellow bar", "editing disabled",
        ),
        "steps": (
            "If you trust the sender and file source, click Enable Editing on the yellow Protected View bar.",
            "Save a copy to Documents or OneDrive and reopen the copy if the file came from email or a download.",
            "Right-click the file, open Properties, and unblock it if Windows marked it as downloaded from the internet.",
            "If company policy blocks editing, contact support rather than changing Trust Center settings blindly.",
        ),
    },
    {
        "id": "excel_formula_not_calculating",
        "service": "excel",
        "intent": "formatting",
        "title": "Excel formulas are not calculating or show old values",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "excel", "formula", "formulas", "not calculating", "old values",
            "manual calculation", "calculate now", "cell not updating",
            "numbers wrong", "stale formula", "recalculate",
        ),
        "steps": (
            "In Excel, go to Formulas > Calculation Options and set calculation to Automatic.",
            "Press F9 or choose Calculate Now to force the workbook to recalculate.",
            "Check whether formulas are showing as text because the cells are formatted as Text or begin with an apostrophe.",
            "If only one workbook is affected, save a copy and test the formulas in the copy before changing global Excel settings.",
        ),
    },
    {
        "id": "excel_pivot_refresh_failed",
        "service": "excel",
        "intent": "sync",
        "title": "Excel pivot table or data refresh fails",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "excel", "pivot", "pivot table", "refresh", "data refresh",
            "refresh failed", "connection", "external data", "query",
            "power query", "data source", "refresh all",
            "pivot refresh", "refresh still failed",
        ),
        "steps": (
            "Go to Data > Queries & Connections and check which connection is failing.",
            "Confirm the source file, SharePoint list, or database is reachable with your current account.",
            "Refresh one query at a time so the exact failing source is visible.",
            "If credentials are stale, clear or update the data source credentials before running Refresh All again.",
        ),
    },
    {
        "id": "powerpoint_video_playback",
        "service": "powerpoint",
        "intent": "crash",
        "title": "PowerPoint embedded video or audio will not play",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "powerpoint", "video", "audio", "media", "embedded video",
            "embedded audio", "will not play", "won't play", "wont play",
            "no sound", "black video", "codec", "playback",
            "slide deck video", "video is black", "still black",
            "media playback", "video playback",
        ),
        "steps": (
            "Open the deck in PowerPoint desktop rather than the browser if the media is embedded.",
            "Select the media and check Playback options, volume, and whether it is set to start automatically or on click.",
            "Use File > Info > Optimize Media Compatibility if PowerPoint offers it.",
            "If the media fails on one computer only, update Office and Windows media components before rebuilding the slide.",
        ),
    },
    {
        "id": "powerpoint_fonts_changed",
        "service": "powerpoint",
        "intent": "formatting",
        "title": "PowerPoint fonts or layout changed on another computer",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "powerpoint", "font", "fonts", "layout changed", "slides shifted",
            "text moved", "wrong font", "missing font", "deck looks different",
            "presentation looks different", "formatting changed",
        ),
        "steps": (
            "Open the deck on the affected computer and note which fonts are being substituted.",
            "Install the missing font if it is approved for that device, or replace it with a standard Office font.",
            "Use File > Options > Save > Embed fonts in the file if the deck must travel between computers.",
            "Export a PDF copy before presenting if exact layout matters and the destination computer is uncertain.",
        ),
    },
    # ---------------------------------------------------------------- WINDOWS
    {
        "id": "windows_printer_queue_stuck",
        "service": "windows",
        "intent": "printing",
        "title": "Windows print queue is stuck or jobs will not print",
        "source": "Local Windows support playbook",
        "keywords": (
            "windows", "printer", "print queue", "stuck printing",
            "print job", "cannot print", "can't print", "cant print",
            "queued", "printer offline", "spooler", "not printing",
        ),
        "steps": (
            "Open Settings > Bluetooth & devices > Printers & scanners and open the printer queue.",
            "Cancel stuck jobs, then turn the printer off and back on.",
            "Restart Windows if the queue will not clear because the print spooler may be stuck.",
            "If jobs return to the queue but never print, remove and re-add the printer.",
        ),
    },
    {
        "id": "windows_wifi_no_internet",
        "service": "windows",
        "intent": "sync",
        "title": "Windows Wi-Fi connected but no internet",
        "source": "Local Windows support playbook",
        "keywords": (
            "windows", "wifi", "wi-fi", "connected no internet", "no internet",
            "network", "wireless", "internet not working", "dns", "limited",
            "cannot connect", "can't connect", "cant connect",
        ),
        "steps": (
            "Toggle Wi-Fi off and back on, then reconnect to the network.",
            "Open Settings > Network & internet and run the network troubleshooter.",
            "Forget the Wi-Fi network and reconnect with the current password.",
            "If other devices are also offline, the issue is likely the network or internet service rather than this Windows device.",
        ),
    },
    {
        "id": "windows_hello_pin_broken",
        "service": "windows",
        "intent": "sign_in",
        "title": "Windows Hello PIN or fingerprint is not working",
        "source": "Local Windows support playbook",
        "keywords": (
            "windows", "hello", "pin", "fingerprint", "face unlock",
            "windows hello", "pin not working", "forgot pin",
            "sign in option", "biometric", "camera sign in",
        ),
        "steps": (
            "On the sign-in screen, choose Sign-in options and try your password as a backup.",
            "After signing in, go to Settings > Accounts > Sign-in options and remove then recreate the PIN or biometric method.",
            "If the PIN reset requires a Microsoft account prompt, complete that prompt without sharing any code in chat.",
            "If this is a managed work device and the PIN reset is blocked, support may need to reset the Windows Hello policy state.",
        ),
    },
    {
        "id": "windows_bitlocker_recovery",
        "service": "windows",
        "intent": "sign_in",
        "title": "Windows is asking for a BitLocker recovery key",
        "source": "Local Windows support playbook",
        "keywords": (
            "windows", "bitlocker", "recovery key", "blue recovery screen",
            "enter recovery key", "locked drive", "drive recovery",
            "cannot boot", "can't boot", "cant boot",
        ),
        "steps": (
            "Do not guess the recovery key; repeated wrong entries will not unlock the drive.",
            "For a personal Microsoft account, check account.microsoft.com/devices/recoverykey.",
            "For a work or school device, contact IT support because the recovery key is usually stored by the organization.",
            "Note whether the screen appeared after BIOS, hardware, or Windows Update changes because support may need that context.",
        ),
    },
    {
        "id": "windows_sound_wrong_device",
        "service": "windows",
        "intent": "audio",
        "title": "Windows sound is playing through the wrong device",
        "source": "Local Windows support playbook",
        "keywords": (
            "windows", "sound", "audio", "speaker", "headphones",
            "wrong device", "no sound", "sound from monitor",
            "output device", "volume mixer", "bluetooth headset",
        ),
        "steps": (
            "Right-click the speaker icon and open Sound settings.",
            "Under Output, choose the expected speaker, headset, or monitor audio device.",
            "Open Volume mixer and confirm the affected app is not muted or routed to a different output.",
            "If a Bluetooth headset is involved, disconnect and reconnect it after selecting the output device.",
        ),
    },
    # -------------------------------------------------------- MICROSOFT ACCOUNT
    {
        "id": "microsoft_account_mfa_number_matching",
        "service": "microsoft account",
        "intent": "sign_in",
        "title": "Authenticator number matching prompt is not working",
        "source": "Local Microsoft account support playbook",
        "keywords": (
            "microsoft account", "authenticator", "number matching",
            "approve sign in", "push notification", "mfa", "2fa",
            "enter number", "approval", "notification not arriving",
            "cannot approve", "can't approve", "cant approve",
        ),
        "steps": (
            "Keep the sign-in screen open and enter the displayed number into the Authenticator prompt on your phone.",
            "If no prompt appears, open Authenticator manually and refresh the account tile.",
            "Check the phone time, internet connection, and notification permission for Authenticator.",
            "Use another verification method if available; if none work, support needs to reset your MFA methods.",
        ),
    },
    {
        "id": "microsoft_365_cached_work_account",
        "service": "microsoft 365",
        "intent": "sign_in",
        "title": "Office apps keep using an old work or school account",
        "source": "Local Microsoft 365 support playbook",
        "keywords": (
            "microsoft 365", "office", "old account", "wrong account",
            "work account", "school account", "cached account",
            "account mismatch", "keeps signing into", "remove account",
            "access work or school",
        ),
        "steps": (
            "In Windows, go to Settings > Accounts > Access work or school and review connected accounts.",
            "Disconnect old or unused work accounts only if you no longer need them on this device.",
            "Open an Office app, go to File > Account, sign out, then sign in with the correct account.",
            "If the wrong account still appears, remove stale Office credentials from Windows Credential Manager and restart Office.",
        ),
    },
)
